language: haskell
dist: bionic

cabal: "2.4"

matrix:
  include:
    - ghc: "8.6.3"
    - ghc: "8.4.4"

cache:
  directories:
    - $HOME/.cabal/store

addons:
  apt:
    packages:
      - libgtk-3-dev
      - libgirepository1.0-dev

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - cabal --version
  - ghc --version

install:
  - cabal v2-install happy

script:
  - cabal v2-build

